#this is the configuration file of PyMoDAQ

local_path = "default"  #relative to all config files (except this one), log... if this is set to default,
#PyMoDAQ's local folder will be stored using user environment variables, you can otherwise set a path here

[data_saving]
    [data_saving.h5file]
    save_path = "C:\\Data"  #base path where data are automatically saved
    compression_level = 5  # for hdf5 files between 0(min) and 9 (max)

    [data_saving.hsds] #hsds connection option (https://www.hdfgroup.org/solutions/highly-scalable-data-service-hsds/)
    #to save data in pymodaq using hpyd backend towards distant server or cloud (mimicking hdf5 files)
    root_url = 'http://hsds.sebastienweber.fr'
    username = "pymodaq_user"
    pwd = "pymodaq"


[general]
debug_level = 'DEBUG' #either 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'
debug_levels = ['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']

[user]
name = "User name"  # default name used as author in the hdf5 saving files

[network]
    [network.logging]
        [network.logging.user]
        username = "pymodaq_user"
        pwd = "pymodaq"

        [network.logging.sql] #location of the postgresql database server and options where the DAQ_Logger will log data
        ip = "10.47.3.22"
        port = 5432




    [network.tcp-server]
    ip = "10.47.0.39"
    port = 6341