#this is the configuration file of PyMoDAQ
[data_saving]
    [data_saving.h5file]
    save_path = "C:\\Data"  #base path where data are automatically saved
    compression_level = 5  # for hdf5 files between 0(min) and 9 (max)

    [data_saving.hsds] #hsds connection option (https://www.hdfgroup.org/solutions/highly-scalable-data-service-hsds/)
    #to save data in pymodaq using hpyd backend towards distant server or cloud (mimicking hdf5 files)
    root_url = "http://hsds.sebastienweber.fr"
    username = "pymodaq_user"
    pwd = "pymodaq"

[general]
debug_level = "DEBUG" #either "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
debug_levels = ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
check_version = true  #automatically check version at startup

[user]
name = "User name"  # default name used as author in the hdf5 saving files

[network]
    [network.logging]
        [network.logging.user]
        username = "pymodaq_user"
        pwd = "pymodaq"

        [network.logging.sql] #location of the postgresql database server and options where the DAQ_Logger will log data
        ip = "10.47.3.22"
        port = 5432

    [network.tcp-server]
    ip = "10.47.0.39"
    port = 6341

[presets]
default_preset_for_scan = "preset_default"
default_preset_for_logger = "preset_default"

[scan]
    scan_in_thread = true
    default = "Scan1D"
    Naverage = 1  # minimum is 1
    steps_limit = 1000  # the limit of the number of steps you can set in a given scan

    [scan.timeflow]
    wait_time = 0
    wait_time_between = 0
    timeout = 10000  # in millisecond

    [scan.scan1D]
    type = "Linear" # either "Linear", "Adaptive", "Linear back to start", "Random" see pymodaq.daq_utils.scanner.py
    start = 1.0
    stop = 2.0
    step = 0.01

    [scan.scan2D]
    type = "Spiral" # either "Spiral", "Linear", "Adaptive", "Back&Forth", "Random" see pymodaq.daq_utils.scanner.py
    start1 = -5
    start2 = -5
    stop1 = 5
    stop2 = 5
    step1 = 0.1
    step2 = 0.1
    npts = 10

    [scan.tabular]
    type = "Linear" #either "Linear", "Adaptive" see pymodaq.daq_utils.scanner.py
    curvilinear = 0.1