name: Base

on:
    workflow_call:
      inputs:
        python:
          required: true
          type: string
        qt5:
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
      QT_DEBUG_PLUGINS: 1
    steps:
      - name: Set up Python ${{ inputs.python }}
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python }}
      - name: Install package
        run: |
          sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
          python -m pip install --upgrade pip
          export QT_DEBUG_PLUGINS=1
          pip install flake8 pytest pytest-cov pytest-qt pytest-xdist pytest-xvfb setuptools wheel numpy h5py ${{ inputs.qt5 }}
          git branch
          pip install -e .    
      - name: create local pymodaq folder and setting permissions
        run: |
          sudo mkdir /etc/.pymodaq
          sudo chmod uo+rw /etc/.pymodaq
      - name: Linting with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=src/pymodaq/resources/QtDesigner_Ressources,docs
      - name: Test with pytest
        run: |
          pytest --cov=pymodaq --cov-report=xml -n auto
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
